### ISSUE TITLE
Design patterns

### ISSUE THREAD

**Issue by ahmethudaiaydin** [Reboot01/Guess-The-Number#3]
Can you imagine to write this game without using "else if" ?

**Comment by Reboot01** [comment]
Can I ask why you want it to be written without "else if" statements?

**Comment by ahmethudaiaydin** [comment]
There are some principles in coding like SOLID. Not to use "else if" reduces complexity. Therefore it should not be prefered. I just thought you'r a new learner.

**Comment by BytewaveMLP** [comment]
This is nothing but a basic guess the number game made to get @Reboot01's feet wet with programming. I don't think it's worthwhile to explore this minor optimization for a 61-line C# game. Concerns over  SOLID principles and cyclomatic complexity are better directed elsewhere instead of confusing new programmers with confusing terms.

You're welcome to submit a PR if you can describe your changes in a teaching manor. But otherwise, this really isn't worthwhile to go into.

**Edit:** On closer examination, I don't even see what would be violating SOLID here. First off, this isn't even OO—it's just procedural logic. Second, a string of `else if`s isn't invalid in SOLID unless you're looking at Open-Closed, which is more for testing object types. And I'd like to think this code doesn't have *that* high of a cyclomatic complexity score.

**Comment by ahmethudaiaydin** [comment]
As I said, I thought you were a new learner, and maybe you want to refactor your code according to some principles. I just advised, not a big deal.

**Comment by BytewaveMLP** [comment]
Those principles aren't really that applicable here anyway. Even if there were some, I'd argue that those principles shouldn't be hailed as gospel.

I understand the idea, but it's best to let them learn at their own pace rather than confusing them with all the extra responsibilities. For small projects, even if those principles are applicable, I have my doubts as to how much they'd actually matter. In my mind, it's best to learn proper code style as you start making larger projects, so you a) have more experience and understanding, and b) know when to apply those principles and when to not waste your time.
